version: '3.9'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./server-side/.env
    ports:
      - 5434:5432

  server:
    build: 
      context: ./server-side
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: ./server-side/.env
    command: sh -c 'yarn typeorm migration:run -d src/data-source && yarn dev'
    ports:
      - 3000:3000

  client:
    depends_on:
      - server
    build:
      context: ./client-side
    ports:
      - 3001:3000
    command: yarn start